name       : libportal
version    : '0.4'
release    : 3
source     :
    - https://github.com/flatpak/libportal/releases/download/0.4/libportal-0.4.tar.xz : 3cd5f50907831cf236b40aa14c5a14ccbbf08828cecb3286efa82ce03cacef28
license    : GPL-2.0-or-later
component  : desktop.library
summary    : libportal provides GIO-style async APIs for most Flatpak portals.
description: |
    libportal provides GIO-style async APIs for most Flatpak portals.
setup      : |
    %meson_configure -Dgtk_doc=false
build      : |
    %ninja_build
install    : |
    %ninja_install
