name       : libportal
version    : 0.3
release    : 1
source     :
    - https://github.com/flatpak/libportal/releases/download/0.3/libportal-0.3.tar.xz : fd35d66357169e63e33ef46c43fdf22ddc07dbd960ec3462b58ca9ef15a65bd7
license    : GPL-2.0-or-later
component  : desktop.library
summary    : libportal provides GIO-style async APIs for most Flatpak portals.
description: |
    libportal provides GIO-style async APIs for most Flatpak portals.
setup      : |
    %patch -p1 < $pkgfiles/0001-Don-t-force-docs-to-be-enabled.patch
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
