name       : libportal
version    : '0.6'
release    : 4
source     :
    - https://github.com/flatpak/libportal/releases/download/0.6/libportal-0.6.tar.xz : 88a12c3ba71bc31acff7238c280de697d609cebc50830c3766776ec35abc6566
license    : GPL-2.0-or-later
component  : desktop.library
summary    : libportal provides GIO-style async APIs for most Flatpak portals.
description: |
    libportal provides GIO-style async APIs for most Flatpak portals.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gtk4)
    - pkgconfig(Qt5X11Extras)
    - vala
setup      : |
    %meson_configure -Ddocs=false
build      : |
    %ninja_build
install    : |
    %ninja_install
